# Generated by Django 4.1.1 on 2022-09-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_fname', models.CharField(max_length=30)),
                ('student_lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_no', models.PositiveIntegerField()),
                ('aadhar_no', models.PositiveIntegerField()),
                ('college_registerid', models.PositiveIntegerField()),
            ],
        ),
    ]
